# Generated by Django 5.1.1 on 2024-09-27 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_alter_sensordata_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
