# Generated by Django 5.1.1 on 2024-10-04 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_images_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='tempereture',
            new_name='temperature',
        ),
    ]
