# Generated by Django 5.1.2 on 2024-10-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_gscoordinates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='temperature',
            new_name='image',
        ),
    ]
