# Generated by Django 5.1.2 on 2024-10-19 09:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_rename_temperature_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
