# Generated by Django 5.1.1 on 2024-10-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_batt_humidity_smoke_soilph_soilprecipitation_and_more'),
        ('Backend', '0011_images_image_name'),
    ]

    operations = [
    ]
