# Generated by Django 5.1.1 on 2024-11-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0013_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinates',
            old_name='latitude',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='coordinates',
            name='longitude',
        ),
    ]
