# Generated by Django 5.1.1 on 2024-12-01 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0015_remove_location_location_location_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_moisture', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('smoke_level', models.FloatField()),
                ('soil_ph', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sat_temp', models.FloatField()),
                ('batt', models.FloatField()),
                ('pressure', models.FloatField()),
                ('yaw', models.FloatField()),
                ('pitch', models.FloatField()),
                ('roll', models.FloatField()),
                ('eps_temp', models.FloatField()),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='batt',
        ),
        migrations.DeleteModel(
            name='humidity',
        ),
        migrations.DeleteModel(
            name='location',
        ),
        migrations.DeleteModel(
            name='smoke',
        ),
        migrations.DeleteModel(
            name='soilph',
        ),
        migrations.DeleteModel(
            name='soilprecipitation',
        ),
        migrations.DeleteModel(
            name='temperature',
        ),
        migrations.RenameField(
            model_name='coordinates',
            old_name='location',
            new_name='latitude',
        ),
        migrations.AddField(
            model_name='coordinates',
            name='longitude',
            field=models.FloatField(1.000000),
            preserve_default=False,
        ),
    ]
