# Generated by Django 5.1.1 on 2024-12-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0016_payload_telemetry_delete_batt_delete_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
