# Generated by Django 5.1.1 on 2024-12-01 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0017_alter_coordinates_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinates',
            old_name='updated_at',
            new_name='timestamp',
        ),
    ]
