# Generated by Django 5.1.1 on 2025-01-11 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0019_payload_created_at_telemetry_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetry',
            name='altitude',
            field=models.FloatField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telemetry',
            name='humidity',
            field=models.FloatField(default=4),
            preserve_default=False,
        ),
    ]
