# Generated by Django 5.1.1 on 2025-01-11 15:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0020_telemetry_altitude_telemetry_humidity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telemetry',
            old_name='voltage',
            new_name='current1',
        ),
        migrations.RenameField(
            model_name='telemetry',
            old_name='current',
            new_name='current2',
        ),
        migrations.AddField(
            model_name='telemetry',
            name='voltage1',
            field=models.FloatField(default=2.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telemetry',
            name='voltage2',
            field=models.FloatField(default=2.0),
            preserve_default=False,
        ),
    ]
