# Generated by Django 5.1.1 on 2025-01-11 15:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0021_rename_voltage_telemetry_current1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetry',
            name='lat',
            field=models.FloatField(default=4.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telemetry',
            name='lon',
            field=models.FloatField(default=4.0),
            preserve_default=False,
        ),
    ]
