# Generated by Django 5.1.1 on 2025-01-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0022_telemetry_lat_telemetry_lon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telemetry',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='telemetry',
            name='lon',
        ),
    ]
