# Generated by Django 5.1.1 on 2025-01-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0023_remove_telemetry_lat_remove_telemetry_lon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image_name',
        ),
    ]
