# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - AgriXcubesat

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
        
      
      - name: Install dependencies
        run: |
          cd AgritechSat
          pip install -r requirements.txt
          cat requirements.txt

        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      - name: startup command
        env:
          MAPBOX: "${{ secrets.MAPBOX }}"
          DATABASECREDS: "${{ secrets.DATABASECREDS }}"
          SECRET_KEY: "${{ secrets.SECRET_KEY }}"
          DEBUG: "True"
        run: |
          cd AgritechSat
          echo $MAPBOX
          echo $DATABASECREDS
          echo $SECRET_KEY
          
      
      - name: Zip artifact for deployment
        run:  |
          cd AgritechSat
           zip -r ../release.zip .

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D77BA98D8AEC478095248ECB031D98DD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2028E22C894C4DCD94B86CD562E11D37 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C22D493EE4954193B2624FB74FB98F33 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'AgriXcubesat'
          slot-name: 'Production'
          
